import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Uber = localFont({
  src: [
    {
      path: "../public/fonts/UberMoveMedium.otf",
      weight: "500",
    },
    {
      path: "../public/fonts/UberMoveBold.otf",
      weight: "700",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Uber.className} min-h-screen font-[500]`}>
        {children}
      </body>
    </html>
  );
}
